version: '3.8'

services:
  zephyr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zephyr-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Mount a volume for model caching to avoid re-downloading the model
      - huggingface-cache:/home/app/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

volumes:
  huggingface-cache:
    name: huggingface-cache
